export let data = [
  {
    folder: "1",
    content: ["1.jpg", "2.jpg", "3.jpg"],
  },
  {
    folder: "10",
    content: ["1.png", "3.png", "4.png", "5.png"],
  },
  {
    folder: "11",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
    ],
  },
  {
    folder: "13",
    content: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
    ],
  },
  {
    folder: "14",
    content: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
      "17.jpg",
      "18.jpg",
    ],
  },
  {
    folder: "15",
    content: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
      "17.jpg",
      "18.jpg",
    ],
  },
  {
    folder: "16",
    content: ["1.jpg", "2.png", "3.png", "4.jpg", "5.png"],
  },
  {
    folder: "2",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
    ],
  },
  {
    folder: "3",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
      "13.png",
      "14.png",
      "15.png",
      "16.png",
      "17.png",
      "18.png",
      "19.png",
      "20.png",
      "21.png",
    ],
  },
  {
    folder: "4",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
      "13.png",
      "14.png",
      "15.png",
      "16.png",
      "17.png",
      "18.png",
      "19.png",
      "20.png",
      "21.png",
      "22.png",
      "23.png",
      "24.png",
      "25.png",
      "26.png",
      "27.png",
      "28.png",
      "29.png",
      "30.png",
      "31.png",
      "32.png",
      "33.png",
      "34.png",
      "35.png",
      "36.png",
      "37.png",
      "38.png",
      "39.png",
      "40.png",
      "41.png",
      "42.png",
      "43.png",
      "44.png",
      "45.png",
      "46.png",
      "47.png",
      "48.png",
      "49.png",
      "50.png",
      "51.png",
      "52.png",
      "53.png",
      "54.png",
      "55.png",
      "56.png",
      "57.png",
      "58.png",
      "59.png",
      "60.png",
      "61.png",
      "62.png",
      "63.png",
      "64.png",
      "65.png",
      "66.png",
      "67.png",
      "68.png",
      "69.png",
      "70.png",
      "71.png",
      "72.png",
      "73.png",
      "74.png",
      "75.png",
      "76.png",
      "77.png",
      "78.png",
      "79.png",
      "80.png",
      "81.png",
      "82.png",
      "83.png",
      "84.png",
      "85.png",
      "86.png",
      "87.png",
      "88.png",
      "89.png",
      "90.png",
      "91.png",
      "92.png",
      "93.png",
      "94.png",
      "95.png",
      "96.png",
      "97.png",
      "98.png",
      "99.png",
    ],
  },
  {
    folder: "5",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
      "13.png",
      "14.png",
      "15.png",
      "16.png",
      "17.png",
      "18.png",
      "19.png",
      "20.png",
      "21.png",
      "22.png",
      "23.png",
      "24.png",
      "25.png",
      "26.png",
      "27.png",
      "28.png",
      "29.png",
      "30.png",
      "31.png",
      "32.png",
      "33.png",
      "34.png",
      "35.png",
      "36.png",
      "37.png",
      "38.png",
      "39.png",
      "40.png",
      "41.png",
      "42.png",
      "43.png",
      "44.png",
      "45.png",
      "46.png",
      "47.png",
      "48.png",
      "49.png",
      "50.png",
      "51.png",
      "52.png",
      "53.png",
      "54.png",
    ],
  },
  {
    folder: "6",
    content: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
      "13.png",
      "14.png",
      "15.png",
      "16.png",
      "17.png",
      "18.png",
      "19.png",
      "20.png",
      "21.png",
      "22.png",
      "23.png",
      "24.png",
      "25.png",
      "26.png",
      "27.png",
      "28.png",
      "29.png",
      "30.png",
      "31.png",
      "32.png",
      "33.png",
      "34.png",
      "35.png",
      "36.png",
      "37.png",
      "38.png",
      "39.png",
      "40.png",
      "41.png",
      "42.png",
      "43.png",
      "44.png",
      "45.png",
      "46.png",
      "47.png",
      "48.png",
      "49.png",
      "50.png",
      "51.png",
      "52.png",
      "53.png",
      "54.png",
      "55.png",
      "56.png",
      "57.png",
      "58.png",
      "59.png",
      "60.png",
    ],
  },
  {
    folder: "7",
    content: ["1.png", "2.png", "3.png", "4.png", "5.png", "6.png"],
  },
  {
    folder: "8",
    content: [
      " 1.jpeg",
      " 2.jpeg",
      " 3.jpeg",
      " 4.jpeg",
      " 5.jpeg",
      " 6.jpeg",
      " 7.jpeg",
      " 8.jpeg",
      " 9.jpeg",
      " 10.jpeg",
      " 11.jpeg",
      " 12.jpeg",
      " 13.jpeg",
      " 14.jpeg",
      " 15.jpeg",
      " 16.jpeg",
      " 17.jpeg",
      " 18.jpeg",
      " 19.jpeg",
      " 20.jpeg",
      " 21.jpeg",
      " 22.jpeg",
      " 23.jpeg",
      " 24.jpeg",
      " 25.jpeg",
      " 26.jpeg",
      " 27.jpeg",
      " 28.jpeg",
      " 29.jpeg",
      " 30.jpeg",
      " 31.jpeg",
      " 32.jpeg",
      " 33.jpeg",
      " 34.jpeg",
      " 35.jpeg",
      " 36.jpeg",
      " 37.jpeg",
      " 38.jpeg",
      " 39.jpeg",
      " 40.jpeg",
      " 41.jpeg",
      " 42.jpeg",
      " 43.jpeg",
      " 44.jpeg",
      " 45.jpeg",
      " 46.jpeg",
      " 47.jpeg",
      " 48.jpeg",
      " 49.jpeg",
      " 50.jpeg",
      " 51.jpeg",
      " 52.jpeg",
      " 53.jpeg",
      " 54.jpeg",
      " 55.jpeg",
      " 56.jpeg",
    ],
  },
  {
    folder: "9",
    content: [
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
    ],
  },
  null,
];
